(function(){
const plansTab=document.createElement('button');plansTab.textContent='Plans';plansTab.onclick=function(){tab('plans',plansTab);loadPlans()};
document.querySelector('.nav').appendChild(plansTab);
const page=document.createElement('section');page.id='plans';page.className='page';page.innerHTML='<div class="card"><h3>Subscription Plans</h3><div class="notice">Live plan controls. Changes are saved to Supabase and used by the Mini App.</div><div class="form"><div class="field"><label>ID</label><input id="planId" readonly></div><div class="field"><label>Name</label><input id="planName"></div><div class="field"><label>Price (TON)</label><input id="planPriceTon" type="number" min="0" step="0.001"></div><div class="field"><label>Ad Reward (USD)</label><input id="planRewardUsd" type="number" min="0" step="0.001"></div><div class="field"><label>Duration (days)</label><input id="planDuration" type="number" min="0" step="1"></div><div class="field"><label>Active</label><select id="planActive"><option value="true">Active</option><option value="false">Disabled</option></select></div></div><div style="margin-top:12px"><button class="btn" id="savePlanBtn">Save Plan</button></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>ID</th><th>Plan</th><th>Price</th><th>Reward</th><th>Duration</th><th>Status</th><th></th></tr></thead><tbody id="plansBody"></tbody></table></div>';
document.getElementById('app').appendChild(page);
async function loadPlans(){const d=await api('plans');window.adminPlans=d.plans||[];const body=document.getElementById('plansBody');body.innerHTML=window.adminPlans.map(p=>'<tr><td>'+esc(p.id)+'</td><td><b>'+esc(p.name||p.id)+'</b></td><td>'+Number(p.price_ton||0).toFixed(3)+' TON</td><td>$'+Number(p.ad_reward_usd||0).toFixed(3)+'</td><td>'+Number(p.duration_days||0)+' days</td><td>'+((p.active)?'<span class="pill ok">active</span>':'<span class="pill rejected">off</span>')+'</td><td><button class="btn gray">Edit</button></td></tr>').join('')||'<tr><td colspan="7">No plans found.</td></tr>';body.querySelectorAll('.btn.gray').forEach((b,i)=>b.onclick=function(){fillPlan(window.adminPlans[i])})}
function fillPlan(p){if(!p)return;document.getElementById('planId').value=p.id;document.getElementById('planName').value=p.name||'';document.getElementById('planPriceTon').value=Number(p.price_ton||0);document.getElementById('planRewardUsd').value=Number(p.ad_reward_usd||0);document.getElementById('planDuration').value=Number(p.duration_days||0);document.getElementById('planActive').value=String(p.active)}
async function savePlan(){const id=document.getElementById('planId').value.trim(),name=document.getElementById('planName').value.trim(),price=Number(document.getElementById('planPriceTon').value),reward=Number(document.getElementById('planRewardUsd').value),days=Number(document.getElementById('planDuration').value),active=document.getElementById('planActive').value==='true';if(!id||!name)return alert('Select a plan first.');if(!Number.isFinite(price)||price<0||!Number.isFinite(reward)||reward<0||!Number.isFinite(days)||days<0)return alert('Invalid plan values.');await api('save_plan',{plan:{id,name,price_ton:price,ad_reward_usd:reward,duration_days:Math.trunc(days),active}});await loadPlans();alert('Plan saved.')}
document.getElementById('savePlanBtn').onclick=savePlan;
window.loadPlans=loadPlans;
})();